# Generated by Django 5.0.6 on 2024-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0003_alter_portfolio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestions',
            name='answer',
            field=models.TextField(),
        ),
    ]
